
import React, { useMemo } from 'react';
import { GeneratedUI } from '../types';

interface PreviewFrameProps {
  data: GeneratedUI | null;
}

export const PreviewFrame: React.FC<PreviewFrameProps> = ({ data }) => {
  if (!data) {
    return (
      <div className="h-full flex flex-col items-center justify-center text-gray-500 p-8 text-center">
        <div className="w-16 h-16 rounded-full border-2 border-dashed border-gray-800 flex items-center justify-center mb-4">
          <svg className="animate-pulse w-8 h-8 opacity-20" fill="currentColor" viewBox="0 0 24 24"><path d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg>
        </div>
        <h3 className="text-lg font-medium text-gray-400">Ready to engineer</h3>
        <p className="max-w-xs mt-2 text-sm opacity-60">Describe an interface on the left and Obscura will generate the visual layout and code here.</p>
      </div>
    );
  }

  return (
    <div className="h-full w-full bg-white overflow-auto custom-scrollbar">
      {/* 
        Warning: In a real production app, we would use a library like 'html-react-parser' 
        or a secure iframe. For this demo, we'll use dangerouslySetInnerHTML to render 
        the Tailwind-powered HTML generated by the AI.
      */}
      <style>{`
        /* Inject local Tailwind base resets into the frame container */
        .preview-container * {
          box-sizing: border-box;
        }
      `}</style>
      <div 
        className="preview-container min-h-full"
        dangerouslySetInnerHTML={{ __html: data.code }}
      />
    </div>
  );
};
